name: "ci"

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  Spec:
    if: ${{ github.repository_owner == 'puppetlabs' }}
    # Temporary workaround for allowing locking node_manager less than latest
    # uses: "puppetlabs/cat-github-actions/.github/workflows/module_ci.yml@main"
    uses: "./.github/workflows/module_ci.yml"
    secrets: "inherit"

  Acceptance:
    if: ${{ github.repository_owner == 'puppetlabs' }}
    needs: Spec
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_acceptance.yml@main"
    with:
      flags: "--provision-service"
    secrets: "inherit"
