name: "mend"

on:
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:

  mend:
    uses: "puppetlabs/puppetlabs-peadm/.github/workflows/mend_ruby.yml@main"
    secrets: "inherit"